### ISSUE TITLE
Incorrect links in footballanalysis/Virtual advertising/README.md 

### ISSUE THREAD

**Issue by adnan-azmat** [FootballAnalysis/footballanalysis#2]
The links in the following lines of [this readme](https://github.com/FootballAnalysis/footballanalysis/tree/main/Virtual%20advertising#readme) may be incorrect as all of them redirect to PyTorch website .

```
Download the trained GAN model from this link and put both 2 files into the ./python_codes/LCNN_GAN/GAN/checkpoints/datasets/ directory
Download the trained LCNN model from this link and put it into the ./python_codes/LCNN_GAN/logs/ directory
Change directory to the LCNN_GAN/ directory
Put our dataset in the ./data/worldcup_raw/directory or create your own dataset just like us and put it in the mentioned directory.
```

**Comment by alikarimi120** [comment]
links are correct 
GAN models:

https://drive.google.com/uc?export=download&id=1KDIT5y6cmkK1x9vHOtMMtsB0H9yL9jJn

LCNN model :
https://drive.google.com/uc?export=download&id=1YLS4oyetw_fQaHm7xY_-4k7HMn-QOJkS

**Comment by dkakaie** [comment]
LCNN trained model link is dead.

**Comment by hackersepulveda** [comment]
could you correct the link?

**Comment by PolinaBokova** [comment]
LCNN model link doesn't work. Could you correct the link please?
