### ISSUE TITLE
files missing for Perspective Transformation demo_image.py

### ISSUE THREAD

**Issue by retz8** [FootballAnalysis/footballanalysis#3]
In your GitHub, files such as feature_camera_91k.mat and database_camera_feature_HoG.mat in Perspective Transformation >> python_codes >> data_2 >> features are missing, so demo_image.py throws an error of missing files in the directory.

**Comment by RReis243** [comment]
You can find them in the Bird's eye view section, right at the end, where it says "Download the models from **here**...": https://github.com/FootballAnalysis/footballanalysis/tree/main/Bird's%20eye%20view.

**Comment by alikarimi120** [comment]
Thanks @reis-rodrigo
