### ISSUE TITLE
Error testing Bird's Eye View

### ISSUE THREAD

**Issue by ahartoch** [FootballAnalysis/footballanalysis#7]
Hi Team,

I'm not a python expert, but I'm a soccer enthusiast of technology. I would like to test your bird's eye view, but I come into the following error:

python3 main.py --source testvideo.mov --view  --save
Yolo model loaded!
DeepSort model loaded!
Perspective Transform model loaded!
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    main(opt)
  File "main.py", line 62, in main
    yoloOutput = detector.detect(frame)
  File "/Volumes/LaCie/FootballOpenCV/footballanalysis/Bird's eye view/elements/yolo.py", line 41, in detect
    pred = self.yolo_model(img, augment=False)[0]
  File "/Users/aha/opt/anaconda3/envs/pycvvision/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Volumes/LaCie/FootballOpenCV/footballanalysis/Bird's eye view/yolov5/models/yolo.py", line 116, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/Volumes/LaCie/FootballOpenCV/footballanalysis/Bird's eye view/yolov5/models/yolo.py", line 147, in forward_once
    x = m(x)  # run
  File "/Users/aha/opt/anaconda3/envs/pycvvision/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/aha/opt/anaconda3/envs/pycvvision/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 157, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/Users/aha/opt/anaconda3/envs/pycvvision/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1260, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by amirhossein-kz** [comment]
Dear @ahartoch

Thank you for your interest in our project. You need to downgrade your PyTorch version.
Try this:
```
pip install torchvision==0.10.1
pip install torch==1.9.1 
```
This will solve your problem.

**Comment by ahartoch** [comment]
Hi Amihossein,

 

 Thanks for coming back to me. I’m afraid that for pytorch to work on my Mac Silicon the only available on version:

 

 

torch                1.13.0.dev20220820

torchaudio           0.13.0.dev20220820

torchvision          0.14.0.dev20220820

 

I guess I won’t be able to test your application. 

 

Thanks anyway

 

From: Amirhossein Kazerouni ***@***.***>
Reply to: FootballAnalysis/footballanalysis ***@***.***>
Date: Tuesday, 23 August 2022 at 01:38
To: FootballAnalysis/footballanalysis ***@***.***>
Cc: aha ***@***.***>, Mention ***@***.***>
Subject: Re: [FootballAnalysis/footballanalysis] Error testing Bird's Eye View (Issue #7)

 

Dear @ahartoch

Thank you for your interest in our project. You need to downgrade your PyTorch version.
Try this:
pip install torchvision==0.10.1
pip install torch==1.9.1 
This will solve your problem.

**Comment by amirhossein-kz** [comment]
Oh, sorry to hear that. Maybe you can use Google Colab.

**Comment by ahartoch** [comment]
HI Amirhossein,

 

 I followed you suggestion and I after some fight I have launched the processing of 2 minutes of my u16 team. I cannot use the –view function as I get some error however with the –-save I hope to get the video with the Bird’s eye view.

 

Not quite sure if this is on your future plans but for me it would be great that position of each player could be recorded from the Bird’s eye view to then create a heatmap. This would certainly be an excellent improvement.

 

Thanks for you help. I’m anxious to see the result as this can certainly help me with my team. Should I win the league with my team I will certainly give you and your team credit in Twitter if you have an account.

 

Kind Regards,

Alex

 

From: Amirhossein Kazerouni ***@***.***>
Reply to: FootballAnalysis/footballanalysis ***@***.***>
Date: Tuesday, 23 August 2022 at 22:29
To: FootballAnalysis/footballanalysis ***@***.***>
Cc: aha ***@***.***>, Mention ***@***.***>
Subject: Re: [FootballAnalysis/footballanalysis] Error testing Bird's Eye View (Issue #7)

 

Oh, sorry to hear that. Maybe you can use Google Colab.
